#////////////////////////////////////////////////////////////////////////////////
#/// @struct     nav_msgs/GetMap
#/// @brief      地図取得
#///
#/// 地図を取得するためのサービス型です。
#///
#////////////////////////////////////////////////////////////////////////////////

---
nav_msgs/OccupancyGrid map      #//!< 地図
