#////////////////////////////////////////////////////////////////////////////////
#/// @struct     nav_msgs/GetPlan
#/// @brief      経路取得
#///
#/// 経路を取得するためのサービス型です。
#///
#////////////////////////////////////////////////////////////////////////////////

geometry_msgs/PoseStamped start      #//!< スタート位置・姿勢
geometry_msgs/PoseStamped goal       #//!< ゴール位置・姿勢
float32 tolerance                    #//!< ゴール許容誤差[m]
---
nav_msgs/Path plan                   #//!< 経路
