#////////////////////////////////////////////////////////////////////////////////
#/// @struct     nav_msgs/SetMap
#/// @brief      地図設定
#///
#/// 地図および初期位置を引き渡すためのサービス型です。
#///
#////////////////////////////////////////////////////////////////////////////////

nav_msgs/OccupancyGrid map                                #//!< 地図
geometry_msgs/PoseWithCovarianceStamped initial_pose      #//!< 初期位置・姿勢
---
bool success                                              #//!< 処理結果

