#////////////////////////////////////////////////////////////////////////////////
#/// @struct     move_base_msgs/MoveBase
#/// @brief      MoveBaseアクション
#///
#/// Navigationスタックへ、目標位置・姿勢を指定してロボットの移動を指示し、
#/// フィードバック（現在位置）および結果を受け取るためのアクションです。
#///
#////////////////////////////////////////////////////////////////////////////////

geometry_msgs/PoseStamped target_pose        #//!< 目標位置・姿勢
---
---
geometry_msgs/PoseStamped base_position      #//!< 現在位置・姿勢
