#////////////////////////////////////////////////////////////////////////////////
#/// @struct     std_srvs/Empty
#/// @brief      Empty型
#///
#/// 引数無し（コールのみ）のサービス型です。
#///
#////////////////////////////////////////////////////////////////////////////////

---
